# Generated by Django 4.2.2 on 2023-06-19 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='event',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='foreign_user',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='score',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='user',
        ),
        migrations.AddField(
            model_name='communication',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='communication',
            name='rate',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='communication',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Interlocutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='interlocutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='communications.interlocutor'),
        ),
    ]
