# Generated by Django 4.2.2 on 2023-06-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_communication_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlocutor',
            name='image_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
