# Generated by Django 4.2.2 on 2023-06-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_communication_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interlocutor',
            old_name='user',
            new_name='owner',
        ),
    ]
