# Generated by Django 4.2.2 on 2023-06-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_rating'),
        ('communications', '0003_interlocutor_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='events.event'),
        ),
    ]
