# Generated by Django 4.2.2 on 2023-06-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
