# Generated by Django 4.2.2 on 2023-06-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='rating',
            new_name='rate',
        ),
    ]
