version: "3.9"

services:
  app:
#    build: # Билд нужен только для разработки. В продакшн среде не используется
#      dockerfile: Dockerfile
#      context: .
    image: shameoff/communications_api:latest
    command: gunicorn ProjectConfig.wsgi:application -b "0.0.0.0:${APP_PORT:-9995}"
    container_name: ${APP_CONTAINER_NAME:-communications_api_app}
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG:-0}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    expose:
      - "${APP_PORT:-9995}"
    ports:
      - "${APP_PORT:-9995}:${APP_PORT:-9995}"
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: communications_api_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped