version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5555:8080"
    restart: unless-stopped

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres