version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: shameoff/communications_api:latest
    command: gunicorn ProjectConfig.wsgi:application -b "localhost:${APP_PORT:-9995}"
    expose:
      - "${APP_PORT:-9995}"
    ports:
      - "${APP_PORT:-9995}:${APP_PORT:-9995}"
    restart: unless-stopped

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres