version: "3.9"

services:
  app:
#    build: # Билд нужен только для разработки. В продакшн среде не используется
#      dockerfile: Dockerfile
#      context: .
    image: shameoff/communications_api:latest
    command: > 
      /bin/sh -c "
        python manage.py migrate &&
        python manage.py initadmin && 
        gunicorn config.wsgi:application -b "0.0.0.0:8080"
      "
    container_name: ${APP_CONTAINER_NAME:-communications_api_app}
    depends_on:
      - db
    environment:
      - DEBUG=${DEBUG:-1}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    expose:
      - "${APP_PORT:-8080}"
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: unless-stopped

  db:
    image: postgres:14
    ports: # для разработки, вообще порты в открытую держать не стоит
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    container_name: communications_api_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    restart: unless-stopped

  fileserver:
    image: minio/minio:latest
    container_name: communications_fileserver
    command: minio server /data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_DOMAIN: "api.shameoff.site:19080"
      MINIO_BROWSER_REDIRECT_URL: "https://api.shameoff.site:19080/minio/"
      MINIO_CONSOLE_ADDRESS: ":9090" # тут указывается полный адрес, в нашем случае "localhost:9090"
    ports:
      - "8030:9000"
      - "${MINIO_PORT}:9090"
    volumes:
      - "./minio_data:/data"
