version: "3.9"

services:
  app:
#    build: # Билд нужен только для разработки. В продакшн среде не используется
#      dockerfile: Dockerfile
#      context: .
    image: shameoff/communications_api:latest
    command: gunicorn ProjectConfig.wsgi:application -b "0.0.0.0:${APP_PORT:-9995}"
    container_name: ${APP_CONTAINER_NAME:-communications_api_app}
    environment:
      - DEBUG="${DEBUG:-0}"
    expose:
      - "${APP_PORT:-9995}"
    ports:
      - "${APP_PORT:-9995}:${APP_PORT:-9995}"
    restart: unless-stopped

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres