name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/communications_api:${{ github.sha }} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/communications_api:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push the Docker image to the repository
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/communications_api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Upload static and configs over SCP
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          source: |
            static/*,
            docker-compose.yml,
            nginx.conf,
            scripts/deploy.sh
          target: /var/www/code/communications_api/

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          # Тут стоит сделать переменными порты приложения и хостовой машины, but not today
          script: "|
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chmod +x deploy.sh 
          && echo ${{ secrets.SUDO_PASSWORD }} | sudo -S ./deploy.sh 
          "
