name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build .
          --file Dockerfile
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/communications_api:${{ github.sha }} 
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/communications_api:latest
          --build-arg SUPERUSER_PASSWORD=${{secrets.SUPERUSER_PASSWORD}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push the Docker image to the repository
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/communications_api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v2

      - name: Upload static and configs over SCP
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          source: |
            static/*,
            docker-compose.yml,
            nginx.conf,
            scripts/*
          target: /var/www/code/communications_api/

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.ACTOR_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          # Тут стоит сделать переменной имя сервера, but not today
          script: |
            export MY_EMAIL=${{ secrets.MY_EMAIL }}
            export APP_DOMAIN=api.shameoff.site
            export APP_NAME=communications_api
            export APP_PORT=9996
            cd /var/www/code/$APP_NAME
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chmod +x scripts/*.sh 
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S -E APP_DOMAIN=$APP_DOMAIN APP_NAME=$APP_NAME APP_PORT=$APP_PORT scripts/start_app.sh
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S -E APP_DOMAIN=$APP_DOMAIN APP_NAME=$APP_NAME MY_EMAIL=$MY_EMAIL APP_PORT=$APP_PORT scripts/nginx_certbot_cronjob.sh
